<a href="https://colab.research.google.com/github/Doclikam/machine-learning3/blob/main/week3_deep%20learning/dlpractice/learningtensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BRAIN TUMOUR CLASSIFICATION**

we are going to learn deep learning with brain tumor classification, understanding the coding and recapping on old concepts

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [ ]:
import tensorflow as tf
from tensorflow.keras.model import Model, Sequential
from tensorflor.keras.layers import Input, Dense, Flatten, Conv2D, Dropout, MaxPooling2D, BatchNormalization, GlobalAveragePooling2D



x=tf.variable([1.,2.], dtype=tf.float64
x handle a mutable tensor which can survive during multiple execution, the trainable parameters: weights, biases are stored in tensors held in variables.

high level archietcture
1st layer:device layer: contains implementation to communicate with diffferent devices such as cpu, gpu, or tpu in the operating system.
network layer: has implementation to communicate to different machines using network protocols
2nd layer: kernel implemenations const, var,conv2d, Relu,MatMul

In [ ]:
import tensorflow as tf

In [ ]:
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x=tf.constant(4.0, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
x=tf.constant([[3,4,5],[5,7,8]], shape=(2,3), dtype=tf.float32)
print(x)

tf.Tensor(
[[3. 4. 5.]
 [5. 7. 8.]], shape=(2, 3), dtype=float32)


In [ ]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
tf.eye

TypeError: Missing required positional argument